SELECT ?var3
WHERE {
?var1 <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q1298292> . OPTIONAL { ?var1 <http://www.wikidata.org/prop/direct/P17> ?var3 . } OPTIONAL { ?var1 <http://www.wikidata.org/prop/direct/P433> ?var4 . } OPTIONAL { ?var1 <http://www.wikidata.org/prop/direct/P585> ?var5 . } OPTIONAL { ?var1 <http://www.wikidata.org/prop/direct/P276> ?var6 . }
}