PREFIX gr: <http://purl.org/goodrelations/>
PREFIX sorg: <http://schema.org/>
PREFIX wsdbm: <http://db.uwaterloo.ca/~galuc/wsdbm/>
PREFIX ex: <http://example.org/>
SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9(concat("(⊕",group_concat(?fprov),")")AS ?f) WHERE {
    
     ?fprov0 rdf:subject ?v0 ; rdf:predicate gr:includes ; rdf:object ?v1 . 
  ?fprov1 rdf:subject wsdbm:Retailer3777 ; rdf:predicate gr:offers ; rdf:object ?v0 .  
    ?fprov2 rdf:subject ?v0 ; rdf:predicate gr:price ; rdf:object ?v3 . 
     ?fprov3 rdf:subject ?v0 ; rdf:predicate gr:serialNumber ; rdf:object ?v4 . 
      ?fprov4 rdf:subject ?v0 ; rdf:predicate gr:validFrom ; rdf:object ?v5 .  
     ?fprov5 rdf:subject ?v0 ; rdf:predicate gr:validThrough ; rdf:object ?v6 . 
     ?fprov6 rdf:subject ?v0 ; rdf:predicate sorg:eligibleQuantity ; rdf:object ?v7 .
    ?fprov7 rdf:subject ?v0 ; rdf:predicate sorg:eligibleRegion ; rdf:object ?v8 . 
    ?fprov8 rdf:subject ?v0 ; rdf:predicate sorg:priceValidUntil ; rdf:object ?v9 .
            BIND(concat(" (⊗",STR(?fprov0),STR(?fprov1),STR(?fprov2),STR(?fprov3),STR(?fprov4),STR(?fprov5),STR(?fprov6),STR(?fprov7),STR(?fprov8), ")")AS ?fprov)
	
}group by ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9

