SELECT ?var3
WHERE {
?var1 <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q13442814> . ?var1 <http://www.wikidata.org/prop/direct/P1476> ?var4 . OPTIONAL { ?var1 <http://www.wikidata.org/prop/direct/P18> ?var3 . }
}