PREFIX gn: <http://www.geonames.org/ontology#>
PREFIX sorg: <http://schema.org/>
PREFIX wsdbm: <http://db.uwaterloo.ca/~galuc/wsdbm/>
PREFIX ex: <http://example.org/>

SELECT ?v0 ?v1 ?v3  (concat("(⊕",group_concat(?fprov),")")AS ?f) WHERE {
                      ?fprov0 rdf:subject ?v0 ; rdf:predicate sorg:jobTitle ; rdf:object ?v1 .
                      ?fprov1 rdf:subject wsdbm:City75 ; rdf:predicate gn:parentCountry ; rdf:object ?v3 .
                      ?fprov2 rdf:subject ?v0 ; rdf:predicate sorg:nationality ; rdf:object ?v3 .
                         
      BIND(concat(" (⊗",STR(?fprov0),STR(?fprov1),STR(?fprov2), ")")AS ?fprov)
     }group by ?v0 ?v1 ?v3

