PREFIX foaf: <http://xmlns.com/foaf/>
PREFIX mo: <http://purl.org/ontology/mo/>
PREFIX sorg: <http://schema.org/>
PREFIX wsdbm: <http://db.uwaterloo.ca/~galuc/wsdbm/>
PREFIX ex: <http://example.org/>
SELECT ?v0 ?v2 ?v3 (concat("(⊕",group_concat(?fprov),")")AS ?f) WHERE {
   
       
?fprov0 rdf:subject ?v0 ; rdf:predicate foaf:age ; rdf:object wsdbm:AgeGroup6 .
    ?fprov1 rdf:subject ?v0 ; rdf:predicate foaf:familyName ; rdf:object ?v2 . 
   ?fprov2 rdf:subject ?v3 ; rdf:predicate mo:artist ; rdf:object ?v0 . 
      ?fprov3 rdf:subject ?v0 ; rdf:predicate sorg:nationality ; rdf:object wsdbm:Country1 . 

            BIND(concat(" (⊗",STR(?fprov0),STR(?fprov1),STR(?fprov2),STR(?fprov3), ")")AS ?fprov)
	
}group by ?v0 ?v2 ?v3 

