PREFIX ex: <http://example.org/>
PREFIX wsdbm: <http://db.uwaterloo.ca/~galuc/wsdbm/>
select ?v0  (concat("(⊕",group_concat(?fprov),")")AS ?f) where {                          
                      
                              	<<?v0  wsdbm:likes  ?v1 >> ex:occurrenceOf ?fprov0. 
                                 <<?v0  wsdbm:subscribes  wsdbm:Website4146 >> ex:occurrenceOf ?fprov1. 
                      BIND(concat(" (⊗",STR(?fprov0),STR(?fprov1),")")AS ?fprov)
                              
    }group by ?v0 
