PREFIX og: <http://ogp.me/ns#>
PREFIX sorg: <http://schema.org/>
PREFIX wsdbm: <http://db.uwaterloo.ca/~galuc/wsdbm/>
PREFIX ex: <http://example.org/>

SELECT ?v0 ?v2  (concat("(⊕",group_concat(?fprov),")")AS ?f) WHERE {
           ?fprov0 rdf:subject ?v0 ; rdf:predicate og:tag ; rdf:object wsdbm:Topic88 .
                   ?fprov1 rdf:subject ?v0 ; rdf:predicate sorg:caption ; rdf:object ?v2 .
                              
    
      BIND(concat(" (⊗",STR(?fprov0),STR(?fprov1), ")")AS ?fprov)
     }group by ?v0 ?v2 

