PREFIX ex: <http://example.org/>
PREFIX foaf: <http://xmlns.com/foaf/>
PREFIX og: <http://ogp.me/ns#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX sorg: <http://schema.org/>
PREFIX wsdbm: <http://db.uwaterloo.ca/~galuc/wsdbm/>
SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 (concat("(⊕",group_concat(?fprov),")")AS ?f) WHERE {
 GRAPH ?fprov0 {?v0 foaf:homepage ?v1 . } 
 GRAPH ?fprov1 {?v0 og:title ?v2 . } 
  GRAPH ?fprov2 {?v0 rdf:type ?v3 . } 
   GRAPH ?fprov3 { ?v0 sorg:caption ?v4 . } 
 GRAPH ?fprov4 { ?v0 sorg:description ?v5 . } 
  GRAPH ?fprov5 {?v1 sorg:url ?v6  . } 
   GRAPH ?fprov6 { ?v1 wsdbm:hits ?v7 . } 
 GRAPH ?fprov7 { ?v0 wsdbm:hasGenre wsdbm:SubGenre69 . } 
            BIND(concat(" (⊗",STR(?fprov0),STR(?fprov1),STR(?fprov2),STR(?fprov3),STR(?fprov4),STR(?fprov5),STR(?fprov6),STR(?fprov7), ")")AS ?fprov)
	
}group by ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 

