PREFIX sorgp: <http://example.org/p/schema.org/>
PREFIX sorgps: <http://example.org/ps/schema.org/>
PREFIX wsdbmp: <http://example.org/p/db.uwaterloo.ca/~galuc/wsdbm/>
PREFIX wsdbmps: <http://example.org/ps/db.uwaterloo.ca/~galuc/wsdbm/>
PREFIX wsdbm: <http://db.uwaterloo.ca/~galuc/wsdbm/>
PREFIX ex: <http://example.org/>
SELECT ?v0  (concat("(⊕",group_concat(?fprov),")")AS ?f) WHERE {
    
?v0 wsdbmp:subscribes ?fprov0 . ?fprov0 wsdbmps:subscribes wsdbm:Website10096 .
?v2 sorgp:caption ?fprov1 . ?fprov1 sorgps:caption ?v3 .
?v0 wsdbmp:likes ?fprov2 . ?fprov2 wsdbmps:likes ?v2 .  
      BIND(concat(" (⊗",STR(?fprov0),STR(?fprov1),STR(?fprov2), ")")AS ?fprov)
     }group by ?v0
