PREFIX sorg: <http://schema.org/>
PREFIX wsdbm: <http://db.uwaterloo.ca/~galuc/wsdbm/>
PREFIX ex: <http://example.org/>
SELECT ?v0  (concat("(⊕",group_concat(?fprov),")")AS ?f) WHERE {
                  <<?v0 wsdbm:subscribes wsdbm:Website10096>> ex:occurrenceOf ?fprov0. 
                	<<   ?v2 sorg:caption ?v3  >> ex:occurrenceOf ?fprov1. 
                 << ?v0 wsdbm:likes ?v2 >> ex:occurrenceOf ?fprov2. 
    
      BIND(concat(" (⊗",STR(?fprov0),STR(?fprov1),STR(?fprov2), ")")AS ?fprov)
     }group by ?v0
