SELECT ?var2
WHERE {
?var1 <http://www.wikidata.org/prop/direct/P1454> <http://www.wikidata.org/entity/Q11448283> . OPTIONAL { ?var1 <http://www.wikidata.org/prop/direct/P3225> ?var2 . } OPTIONAL { ?var1 <http://www.wikidata.org/prop/direct/P17> ?var3 . }
}