SELECT ?var2
WHERE {
?var1 <http://www.wikidata.org/prop/direct/P1802> ?var5 . OPTIONAL { ?var1 <http://www.wikidata.org/prop/direct/P18> ?var2 . } OPTIONAL { ?var1 <http://www.wikidata.org/prop/direct/P106> ?var3 . }
}