SELECT ?var2
WHERE {
?var1 <http://www.wikidata.org/prop/direct/P306> <http://www.wikidata.org/entity/Q14656> . ?var1 <http://www.wikidata.org/prop/direct/P348> ?var2 . OPTIONAL { ?var1 <http://www.wikidata.org/prop/direct/P856> ?var3 . }
}