PREFIX wsdbm: <http://db.uwaterloo.ca/~galuc/wsdbm/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX mo: <http://purl.org/ontology/mo/>
PREFIX ex: <http://example.org/>
SELECT ?v0  (concat("(⊕",group_concat(?fprov),")")AS ?f) WHERE {
    
            GRAPH ?fprov0 { ?v0  mo:conductor  ?v1  . } 
            GRAPH ?fprov1 { ?v0  rdf:type  ?v2 . } 
           GRAPH ?fprov2 {?v0  wsdbm:hasGenre  wsdbm:SubGenre8 . } 
                       
      BIND(concat(" (⊗",STR(?fprov0),STR(?fprov1),STR(?fprov2), ")")AS ?fprov)
     }group by ?v0
