SELECT ?var1 (CONCAT("⊕(",GROUP_CONCAT(?fprov) ,")")  AS ?finalprovennacevariable) 
WHERE { 
	?var1 <http://www.wikidata.org/prop/P131> ?fprov0 . 
	?fprov0 <http://www.wikidata.org/prop/statement/P131> <http://www.wikidata.org/entity/Q21590062> . 
	BIND (CONCAT("(⊗",STR(?fprov0) ,",",")")  AS ?fprov) . 
 }
 GROUP BY ?var1