PREFIX gn: <http://www.geonames.org/ontology#>
PREFIX sorg: <http://schema.org/>
PREFIX wsdbm: <http://db.uwaterloo.ca/~galuc/wsdbm/>
PREFIX ex: <http://example.org/>

SELECT ?v0 ?v1 ?v3  (concat("(⊕",group_concat(?fprov),")")AS ?f) WHERE {
                         GRAPH ?fprov0 {?v0 sorg:jobTitle ?v1. }
                         GRAPH ?fprov1 { wsdbm:City126 gn:parentCountry ?v3 . } 
                         GRAPH ?fprov2 { ?v0 sorg:nationality ?v3 . } 
                       
    
      BIND(concat(" (⊗",STR(?fprov0),STR(?fprov1),STR(?fprov2), ")")AS ?fprov)
     }group by ?v0 ?v1 ?v3

