PREFIX og: <http://ogp.me/ns#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX sorg: <http://schema.org/>
PREFIX wsdbm: <http://db.uwaterloo.ca/~galuc/wsdbm/>
PREFIX ex: <http://example.org/>
SELECT ?v0 ?v2 ?v3 ?v4 ?v5 (concat("(⊕",group_concat(?fprov),")")AS ?f) WHERE {
 ?fprov0 rdf:subject ?v0 ; rdf:predicate og:tag ; rdf:object wsdbm:Topic67 . 
?fprov1 rdf:subject ?v0 ; rdf:predicate rdf:type ; rdf:object ?v2 . 
  ?fprov2 rdf:subject ?v3 ; rdf:predicate sorg:trailer ; rdf:object ?v4 . 
  ?fprov3 rdf:subject ?v3 ; rdf:predicate sorg:keywords ; rdf:object ?v5 .  
   ?fprov4 rdf:subject ?v3 ; rdf:predicate wsdbm:hasGenre ; rdf:object ?v0 .
   ?fprov5 rdf:subject ?v3 ; rdf:predicate rdf:type ; rdf:object wsdbm:ProductCategory2 . 
            BIND(concat(" (⊗",STR(?fprov0),STR(?fprov1),STR(?fprov2),STR(?fprov3),STR(?fprov4),STR(?fprov5), ")")AS ?fprov)
	
}group by ?v0 ?v2 ?v3 ?v4 ?v5


