PREFIX sorg: <http://schema.org/>
PREFIX wsdbm: <http://db.uwaterloo.ca/~galuc/wsdbm/>
PREFIX ex: <http://example.org/>
PREFIX gn: <http://www.geonames.org/ontology#>
SELECT  ?v0 ?v1 ?v3 (concat("(⊕",group_concat(?funion1),")" )AS ?f)
WHERE {
{SELECT ?v0 ?v1 ?v3 (concat("(⊕",group_concat(?fprov),")" )AS ?fjoin1) WHERE {
          	?fprov0 rdf:subject wsdbm:City199 ; rdf:predicate gn:parentCountry ; rdf:object ?v3 .
                 ?fprov1 rdf:subject ?v0 ; rdf:predicate sorg:nationality ; rdf:object ?v3 .
           ?fprov2 rdf:subject ?v0 ; rdf:predicate sorg:jobTitle ; rdf:object ?v1 .
            BIND(concat(" (⊗",COALESCE(STR(?fprov0),""),COALESCE(STR(?fprov1),""),COALESCE(STR(?fprov2),""),")")AS ?fprov)           
          }group by ?v0 ?v1 ?v2 ?v3}
UNION
{SELECT ?v0 ?v1 ?v3  (concat("(⊖",?fjoin2,group_concat(?fjoin3),")")AS ?fopt1) WHERE {
    {
SELECT ?v0 ?v3  (concat("(⊕",group_concat(?fprov),")")AS ?fjoin2) WHERE {
                 ?fprov0 rdf:subject wsdbm:City199 ; rdf:predicate gn:parentCountry ; rdf:object ?v3 .
                 ?fprov1 rdf:subject ?v0 ; rdf:predicate sorg:nationality ; rdf:object ?v3 .
  
                    BIND(concat(" (⊗",COALESCE(STR(?fprov0),""),COALESCE(STR(?fprov1),""), ")")AS ?fprov)
     }group by ?v0 ?v3 
    }
        OPTIONAL{
                                        
                            { Select ?v0 ?v1 (concat("(⊕",group_concat(?fprov),")" )AS ?fjoin3)
                          where{	 ?fprov2 rdf:subject ?v0 ; rdf:predicate sorg:jobTitle ; rdf:object ?v1 .
                        BIND(concat(" (⊗",COALESCE(STR(?fprov2),""), ")")AS ?fprov)
                          }group by ?v0 ?v1}.
    }
}group by ?v0 ?v1 ?v3 ?fjoin2}  
    BIND(concat(" (⊕",COALESCE(STR(?fjoin1),""),COALESCE(STR(?fopt1),""), ")")AS ?funion1)
}group by ?v0 ?v1 ?v3

