PREFIX wsdbm: <http://db.uwaterloo.ca/~galuc/wsdbm/>
PREFIX sorg: <http://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT ?v0
WHERE {
  ?v0  rdf:type          wsdbm:ProductCategory2 .
  ?v0  sorg:description  ?v2 .
  ?v0  sorg:keywords     ?v3 .
  ?v0  sorg:language     wsdbm:Language0 .
}
