SELECT ?var5
WHERE {
?var1 <http://www.wikidata.org/prop/direct/P3173> ?var2 . OPTIONAL { ?var1 <http://www.wikidata.org/prop/direct/P18> ?var4 . } OPTIONAL { ?var2 <http://www.wikidata.org/prop/direct/P18> ?var5 . }
}