SELECT ?var8
WHERE {
?var1 <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q12546> . OPTIONAL { ?var1 <http://www.wikidata.org/prop/direct/P580> ?var8 . ?var1 <http://www.wikidata.org/prop/direct/P582> ?var9 . }
}