PREFIX wsdbmp: <http://example.org/p/db.uwaterloo.ca/~galuc/wsdbm/>
PREFIX wsdbmps: <http://example.org/ps/db.uwaterloo.ca/~galuc/wsdbm/>
PREFIX wsdbm: <http://db.uwaterloo.ca/~galuc/wsdbm/>
PREFIX dc: <http://purl.org/dc/terms/>
PREFIX dcp: <http://example.org/p/purl.org/dc/terms/>
PREFIX dcps: <http://example.org/ps/purl.org/dc/terms/>
PREFIX sorgp: <http://example.org/p/schema.org/>
PREFIX sorgps: <http://example.org/ps/schema.org/>
PREFIX rdfp: <http://example.org/p/www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfps: <http://example.org/ps/www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX ex: <http://example.org/>
SELECT ?v0  (concat("(⊕",group_concat(?fprov),")")AS ?f) WHERE {
?v0 dcp:Location ?fprov0 . ?fprov0 dcps:Location ?v1 .
?v0 sorgp:nationality ?fprov1 . ?fprov1 sorgps:nationality wsdbm:Country10 .
?v0 wsdbmp:gender ?fprov2 . ?fprov2 wsdbmps:gender ?v3 .
?v0 rdfp:type ?fprov3 . ?fprov3 rdfps:type wsdbm:Role2 .
                  			
      BIND(concat(" (⊗",STR(?fprov0),STR(?fprov1),STR(?fprov2),STR(?fprov3), ")")AS ?fprov)
     }group by ?v0  
