SELECT ?var1 (CONCAT("⊕(",GROUP_CONCAT(?fprov) ,")")  AS ?finalprovennacevariable) 
WHERE { 
	?var1 <http://www.wikidata.org/prop/P106> ?fprov0 . 
	?fprov0 <http://www.wikidata.org/prop/statement/P106> <http://www.wikidata.org/entity/Q593644> . 
	?var1 <http://www.wikidata.org/prop/P21> ?fprov1 . 
	?fprov1 <http://www.wikidata.org/prop/statement/P21> <http://www.wikidata.org/entity/Q6581072> . 
	BIND (CONCAT("(⊗",STR(?fprov0) ,",",STR(?fprov1) ,",",")")  AS ?fprov) . 
 }
 GROUP BY ?var1