SELECT ?var4 (CONCAT("⊕(",GROUP_CONCAT(?fprov) ,")")  AS ?finalprovennacevariable) 
WHERE { 
	?var1 <http://www.wikidata.org/prop/P2044> ?fprov0 . 
	?fprov0 <http://www.wikidata.org/prop/statement/P2044> ?var4 . 
	?var1 <http://www.wikidata.org/prop/P625> ?fprov1 . 
	?fprov1 <http://www.wikidata.org/prop/statement/P625> ?var3 . 
	BIND (CONCAT("(⊗",STR(?fprov0) ,",",STR(?fprov1) ,",",")")  AS ?fprov) . 
 }
 GROUP BY ?var4