SELECT ?var1 (CONCAT("⊕(",GROUP_CONCAT(?fprov) ,")")  AS ?finalprovennacevariable) 
WHERE { 
	?var1 <http://www.wikidata.org/prop/P21> ?fprov0 . 
	?fprov0 <http://www.wikidata.org/prop/statement/P21> <http://www.wikidata.org/entity/Q6581072> . 
	?var1 <http://www.wikidata.org/prop/P27> ?fprov1 . 
	?fprov1 <http://www.wikidata.org/prop/statement/P27> <http://www.wikidata.org/entity/Q16> . 
	?var1 <http://www.wikidata.org/prop/P569> ?fprov2 . 
	?fprov2 <http://www.wikidata.org/prop/statement/P569> ?var3 . 
	BIND (CONCAT("(⊗",STR(?fprov0) ,",",STR(?fprov1) ,",",STR(?fprov2) ,",",")")  AS ?fprov) . 
 }
 GROUP BY ?var1