SELECT ?var3 (CONCAT("⊕(",GROUP_CONCAT(?funion0) ,")")  AS ?finalprovennacevariable) 
WHERE { 
{
{ SELECT ?var1 ?var2 ?var3 (CONCAT("⊕(",GROUP_CONCAT(?fjoin0) ,")")  AS ?rightunion0) 
WHERE { 
	?var1 <http://www.wikidata.org/prop/P106> ?fprov1 . 
	?fprov1 <http://www.wikidata.org/prop/statement/P106> ?var2 . 
	?var2 <http://www.wikidata.org/prop/P18> ?fprov3 . 
	?fprov3 <http://www.wikidata.org/prop/statement/P18> ?var3 . 
	BIND (CONCAT("(⊗",STR(?fprov1) ,",",STR(?fprov3) ,",",")")  AS ?fjoin0) . 
 }
 GROUP BY ?var1 ?var2 ?var3 
 } }
 UNION
{
{ SELECT ?var1 ?var2 ?var3 (CONCAT("(⊖",?rightunion1,",",GROUP_CONCAT(?rightunion2) ,",",")")  AS ?rightoptional1) 
WHERE { 
{ SELECT ?var1 ?var2 (CONCAT("⊕(",GROUP_CONCAT(?fjoin1) ,")")  AS ?rightunion1) 
WHERE { 
	?var1 <http://www.wikidata.org/prop/P106> ?fprov0 . 
	?fprov0 <http://www.wikidata.org/prop/statement/P106> ?var2 . 
	BIND (CONCAT("(⊗",STR(?fprov0) ,",",")")  AS ?fjoin1) . 
 }
 GROUP BY ?var1 ?var2 
 }  OPTIONAL { { SELECT ?var2 ?var3 (CONCAT("⊕(",GROUP_CONCAT(?fjoin2) ,")")  AS ?rightunion2) 
WHERE { 
	?var2 <http://www.wikidata.org/prop/P18> ?fprov2 . 
	?fprov2 <http://www.wikidata.org/prop/statement/P18> ?var3 . 
	BIND (CONCAT("(⊗",STR(?fprov2) ,",",")")  AS ?fjoin2) . 
 }
 GROUP BY ?var2 ?var3 
 } }  }
 GROUP BY ?var1 ?var2 ?var3 ?rightunion1 
 } }
	BIND (CONCAT("(⊕",?rightunion0,",",?rightoptional1,",",")")  AS ?funion0) . 
 }
 GROUP BY ?var3