SELECT ?var1 (CONCAT("⊕(",GROUP_CONCAT(?funion0) ,")")  AS ?finalprovennacevariable) 
WHERE { 
{
{ SELECT ?var1 ?var4 (CONCAT("⊕(",GROUP_CONCAT(?fjoin0) ,")")  AS ?rightunion0) 
WHERE { 
	?var1 <http://www.wikidata.org/prop/P195> ?fprov1 . 
	?fprov1 <http://www.wikidata.org/prop/statement/P195> <http://www.wikidata.org/entity/Q1967614> . 
	?var1 <http://www.wikidata.org/prop/P136> ?fprov3 . 
	?fprov3 <http://www.wikidata.org/prop/statement/P136> ?var4 . 
	BIND (CONCAT("(⊗",STR(?fprov1) ,",",STR(?fprov3) ,",",")")  AS ?fjoin0) . 
 }
 GROUP BY ?var1 ?var4 
 } }
 UNION
{
{ SELECT ?var1 ?var4 (CONCAT("(⊖",?rightunion1,",",GROUP_CONCAT(?rightunion2) ,",",")")  AS ?rightoptional1) 
WHERE { 
{ SELECT ?var1 (CONCAT("⊕(",GROUP_CONCAT(?fjoin1) ,")")  AS ?rightunion1) 
WHERE { 
	?var1 <http://www.wikidata.org/prop/P195> ?fprov0 . 
	?fprov0 <http://www.wikidata.org/prop/statement/P195> <http://www.wikidata.org/entity/Q1967614> . 
	BIND (CONCAT("(⊗",STR(?fprov0) ,",",")")  AS ?fjoin1) . 
 }
 GROUP BY ?var1 
 }  OPTIONAL { { SELECT ?var1 ?var4 (CONCAT("⊕(",GROUP_CONCAT(?fjoin2) ,")")  AS ?rightunion2) 
WHERE { 
	?var1 <http://www.wikidata.org/prop/P136> ?fprov2 . 
	?fprov2 <http://www.wikidata.org/prop/statement/P136> ?var4 . 
	BIND (CONCAT("(⊗",STR(?fprov2) ,",",")")  AS ?fjoin2) . 
 }
 GROUP BY ?var1 ?var4 
 } }  }
 GROUP BY ?var1 ?var4 ?rightunion1 
 } }
	BIND (CONCAT("(⊕",?rightunion0,",",?rightoptional1,",",")")  AS ?funion0) . 
 }
 GROUP BY ?var1